### ISSUE TITLE
How to visualize the results?

### ISSUE THREAD

**Issue by YouSheng-Do** [daveredrum/SceneTex#11]
Thank you for the excellent work! I ran the demo bash and it worked well for me. However, I noticed that the outputs consist of RGB and depth images from different views, rather than 3D models. If possible, could you please share your visualization code? I sincerely appreciate your help and thank you again for your outstanding work. 😊

**Comment by YouSheng-Do** [comment]
Sorry, I just found the texture_{iteration}.png file, so it's good to visualize it now. 😂😂

**Comment by RAJA-PARIKSHAT** [comment]
@YouSheng-Do how did you visualize? Did you use Meshlab to visualize scene.obj with optimized texture?

**Comment by YouSheng-Do** [comment]
> @YouSheng-Do how did you visualize? Did you use Meshlab to visualize scene.obj with optimized texture?

Yes, use Meshlab or Blender with the image as texture and then you can see it.
