### ISSUE TITLE
FlashAttention cuda version issue

### ISSUE THREAD

**Issue by ychgoaround** [daveredrum/SceneTex#2]
Hi Dave,

Thanks for this amazing work and open-sourced your code! However, I noticed that you did install flash-attn on cuda11.3? However flash-attn can only be installed on 11.6 and above according to [the document](https://github.com/Dao-AILab/flash-attention). May I ask how did you solve this issue? Thanks in advance and all the best!

**Comment by daveredrum** [comment]
Hi @ychgoaround, thanks for your interest in our work. Did you try it out on your cuda 11.x environment?

**Comment by ychgoaround** [comment]
Yes, I tried it out on my cuda11.2 environment and if I run pip install flash-attn it reports error with higher cuda version demand

**Comment by daveredrum** [comment]
Emmm it seems this codebase is built upon cuda 11.7. I'm fixing the README right away. Sorry for the confusion.
